version: '3.0'

services:
  frontend:
    build:
      context: ./application/lk-user
    container_name: ${PROJECT_NAME}-frontend
    working_dir: /lkuser
    volumes:
      - ./application/lk-user:/lkuser
    ports:
      - "8080:8080"

  php-fpm:
    build:
      context: ./docker/php
    environment:
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - ./application/lk-user:/lkuser
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - postgres
    working_dir: /lkuser

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: ${PROJECT_NAME}-postgres

  nginx:
    image: nginx:1.19.4-alpine
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_DIR_USER: /lkuser/public
      PHP_FPM: php-fpm
      VIRTUAL_HOST: ${NGINX_HOST}
    working_dir: /
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./docker/nginx/nginx.conf.template:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./docker/nginx/sites-available/:/etc/nginx/sites-enabled/
      - ./application/lk-user:/lkuser
    depends_on:
      - php-fpm
    ports:
      - "80:80"